# Решение задачи 3 (Дюсекеев 101М)
# Вариант 5

**Задание 3** \
$C_{1} =\begin{pmatrix} 1&-1 \\ 1&-2 \end{pmatrix}$

Элемент пространства $V_{k}^{2} $ представлен матрицей $C_{k} $ коэффициентов в базисе, образованном вейвлетами Хаара. Найти матрицы коэффициентов разложения этого элемента по базису пространства $V_{k-1}^{2} \oplus W_{k-1}^{2} $ и пространства $V_{0}^{2} \bigoplus \limits_{j=0}^{k-1} W_{j}^{2} $. Сделать проверку, используя алгоритм вейвлет-восстановления (данная матрица и матрица, полученная восстановлением, должны совпасть).

Элемент пространства $V_{1}^{2} $ с матрицей коэффициентов $C_{1} =\begin{pmatrix} 1&-1 \\ 1&-2 \end{pmatrix}$ разложим по базису пространства $V_{0}^{2} \oplus W_{0}^{2} $. Имеем

$$
{\rm С}_{1} =\begin{pmatrix} 1&-1 \\ 1&-2 \end{pmatrix},~{\rm P}_{1} =\frac{1}{\sqrt{2} } \begin{pmatrix} 1\\1\end{pmatrix},~{\rm Q}_{1} =\frac{1}{\sqrt{2} } \begin{pmatrix} 1\\-1 \end{pmatrix}.
$$

Следовательно,

$$
{\rm C}_{0} ={\rm P}_{1}^{T} {\rm C}_{1} {\rm P}_{1} =\left(-0,5\right);~{\rm R}_{0} ={\rm Q}_{1}^{T} {\rm C}_{1} {\rm P}_{1} =\left(0,5\right);
$$

$$
{\rm H}_{0} ={\rm P}_{1}^{T} {\rm C}_{1} {\rm Q}_{1} =\left(2,5\right);~{\rm D}_{0} ={\rm Q}_{1}^{T} {\rm C}_{1} {\rm Q}_{1} =\left(-0.5\right).
$$





In [35]:

C0 = np.array([[-0.5]])
R0 = np.array([[0.5]])
H0 = np.array([[2.5]])
D0 = np.array([[-0.5]])
print(C0)
print(R0)
print(H0)
print(D0)


[[-0.5]]
[[0.5]]
[[2.5]]
[[-0.5]]


In [38]:
P1 = (1 / math.sqrt(2)) * np.array([[1],[1]])
Q1 = (1 / math.sqrt(2)) * np.array([[1],[-1]])
print(P1)
print(Q1)

[[0.70710678]
 [0.70710678]]
[[ 0.70710678]
 [-0.70710678]]


Проверка

$$
{\rm P}_{1} {\rm C}_{0} {\rm P}_{1}^{T} +{\rm Q}_{1} {\rm R}_{0} {\rm P}_{1}^{T} +{\rm P}_{1} {\rm H}_{0} {\rm Q}_{1}^{T} +{\rm Q}_{1} {\rm D}_{0} {\rm Q}_{1}^{T} ={\rm C}_{1}.
$$

In [40]:
C1 = (P1.dot(C0)).dot(np.transpose(P1))+(Q1.dot(R0)).dot(np.transpose(P1)) + (P1.dot(H0)).dot(np.transpose(Q1)) + (Q1.dot(D0)).dot(np.transpose(Q1))
print(C1)

[[ 1. -1.]
 [ 1. -2.]]
